"""Fix relationship ambiguity in PatientTestRecord

Revision ID: afe02da0da14
Revises: 1a7c0107da60
Create Date: 2025-11-09 14:58:26.086995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe02da0da14'
down_revision = '1a7c0107da60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('patient_test_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('doctor_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('doctor_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('hospital_name', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('request_form_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('verified_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('verified_notes', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('report_path', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'test_categories', ['test_category_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['verified_by'], ['id'])

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('patient_test_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('report_path')
        batch_op.drop_column('status')
        batch_op.drop_column('verified_notes')
        batch_op.drop_column('verified_at')
        batch_op.drop_column('verified_by')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('request_form_path')
        batch_op.drop_column('hospital_name')
        batch_op.drop_column('doctor_email')
        batch_op.drop_column('doctor_name')
        batch_op.drop_column('test_category_id')

    op.drop_table('test_categories')
    # ### end Alembic commands ###
